task_manager/urls.py

from rest_framework.routers import SimpleRouter
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path

from tasks.apiviews import TaskApiViewSet, TaskHistoryApiViewset


def indexRedirect(req):
    return HttpResponseRedirect("tasks/")


router = SimpleRouter()

router.register("api/tasks", TaskApiViewSet, basename='tasks')
router.register("api/history", TaskHistoryApiViewset, basename='history')


urlpatterns = [
    path("admin/", admin.site.urls),
    path('user/', include("user.urls")),
    path('tasks/', include("tasks.urls")),
    path('', indexRedirect)
] + router.urls

tasks/urls.py
from django.urls import path

from .views import (GenereicAllTaskView, GenereicCompletedTaskView,
                    GenereicPendingTaskView, GenericTaskCreateView,
                    GenericTaskDeleteView, GenericTaskDetailView,
                    GenericTaskEmailReportView, GenericTaskUpdateView,
                    complete_Task)

urlpatterns = [

    path('create/', GenericTaskCreateView.as_view()),
    path('delete/<pk>',   GenericTaskDeleteView.as_view()),
    path('update/<pk>', GenericTaskUpdateView.as_view()),
    path('complete/<pk>', complete_Task),
    path('task/<pk>/', GenericTaskDetailView.as_view()),
    path('', GenereicPendingTaskView.as_view()),
    path('all/', GenereicAllTaskView.as_view()),
    path('completed/', GenereicCompletedTaskView.as_view()),
    path('set_reminder/', GenericTaskEmailReportView.as_view()),



]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views


urlpatterns = [
    path("signup/", views.UserCreateView.as_view()),
    path("login/", views.UserLoginView.as_view()),
    path("logout/", LogoutView.as_view())


]

tasks/models.py

from xmlrpc.client import boolean
from django.db import models

from django.contrib.auth.models import User

from django.db.models.signals import pre_save
from django.dispatch import receiver

STATUS_CHOICES = [
    ("P", "PENDING"),
    ("D", "DONE"),
    ("C", "CANCELLED")
]


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    priority = models.SmallIntegerField(default=-1)
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default='P')

    def __str__(self):
        return self.title


class History(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    old_status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, null=True)
    new_status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, null=True)


class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    reminder_time = models.TimeField()
    last_sent_day = models.DateField(null=True, default=None, blank=True)
    disabled = models.BooleanField(default=True)


@receiver(pre_save, sender=Task)
def task_update_trigger(sender, instance, **kwargs):
    new_task = instance
    id = new_task.id
    try:

        old_task = Task.objects.get(pk=id)
        if(new_task.status != old_task.status):
            History.objects.create(
                task=instance, old_status=old_task.status, new_status=new_task.status)

    except:
        print("no task found")

tasks/forms.py

from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from tasks.models import Report, Task

from .models import Task


class TaskCreateForm(LoginRequiredMixin, ModelForm):

    def clean_title(self):
        title = self.cleaned_data["title"]
        if(len(title) < 5):
            raise ValidationError("too small")
        return title.upper()

    def clean_priority(self):
        priority = self.cleaned_data["priority"]
        if(int(priority) < 0):
            raise ValidationError("Priority Cannot be Negative")
        return priority

    class Meta:
        model = Task
        fields = ("title", "description", "priority", "completed", )


class EmailReportForm(LoginRequiredMixin, ModelForm):
    class Meta:
        model = Report
        widgets = {
            'reminder_time': forms.TimeInput(
                attrs={'placeholder': 'HH:MM'}),
        }
        fields = ("reminder_time", "disabled")

tasks/views.py

from re import template
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.core.exceptions import ValidationError

from tasks.models import Task

from .forms import TaskCreateForm, EmailReportForm


def get_pending_tasks(user, priority=-1):
    if priority == -1:
        return Task.objects.filter(deleted=False, completed=False, user=user)
    return Task.objects.filter(deleted=False, completed=False, user=user, priority=priority)


def get_completed_tasks(user):
    return Task.objects.filter(deleted=False, completed=True, user=user)


def get_all_tasks(user):
    return Task.objects.filter(deleted=False,  user=user)


def cascade_Tasks(user, priority):
    tasks_to_update = []
    all_tasks = Task.objects.select_for_update().filter(deleted=False, completed=False,
                                                        user=user, priority__gte=priority).order_by('priority')
    if(all_tasks.filter(priority=priority)).exists():

        with transaction.atomic():
            for task in all_tasks:
                if task.priority == priority:
                    task.priority += 1
                    priority += 1
                    tasks_to_update.append(task)
            Task.objects.bulk_update(tasks_to_update, ['priority'])


def save_Task(self, form):
    self.object = form.save()
    self.object.user = self.request.user
    self.object.save()


class AuthorizedTasksView(LoginRequiredMixin):
    def get_queryset(self):
        return Task.objects.filter(deleted=False).filter(completed=False, user=self.request.user)


class GenericTaskCreateView(LoginRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = "task_create.html"
    success_url = "/tasks"

    def form_valid(self, form):
        priority = form.cleaned_data["priority"]
        user = self.request.user
        cascade_Tasks(user, priority)
        save_Task(self, form)
        return HttpResponseRedirect("/tasks")


class GenereicPendingTaskView(AuthorizedTasksView,  ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "tasks.html"
    context_object_name = "tasks"
    paginate_by = 3

    def get_queryset(self):
        search_item = self.request.GET.get("search")
        tasks = get_pending_tasks(self.request.user)
        if search_item:
            tasks = tasks.filter(title__icontains=search_item)

        return tasks


class GenereicAllTaskView(AuthorizedTasksView,  ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "all_tasks.html"
    context_object_name = "tasks"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        return {'tasks': get_all_tasks(self.request.user),
                'all': get_all_tasks(self.request.user).count(),
                'completed': get_completed_tasks(self.request.user).count()}


class GenereicCompletedTaskView(AuthorizedTasksView,  ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "completed_tasks.html"
    context_object_name = "tasks"
    paginate_by = 3

    def get_queryset(self):
        search_item = self.request.GET.get("search")
        tasks = get_completed_tasks(self.request.user)
        if search_item:
            tasks = tasks.filter(title__icontains=search_item)

        return tasks


class GenericTaskUpdateView(AuthorizedTasksView,  UpdateView):
    model = Task
    form_class = TaskCreateForm
    template_name = "task_update.html"
    success_url = "/tasks"

    def form_valid(self, form):
        priority = form.cleaned_data["priority"]
        user = self.request.user

        if('priority' in form.changed_data):
            cascade_Tasks(user, priority)

        if('status' in form.changed_data):
            print("do stuff")

        save_Task(self, form)

        return HttpResponseRedirect("/tasks")


class GenericTaskDetailView(AuthorizedTasksView, DetailView):
    model = Task
    template_name = "task_detail.html"


class GenericTaskDeleteView(AuthorizedTasksView, DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = "/tasks"


def complete_Task(req, pk):
    Task.objects.filter(id=pk).update(completed=True)
    return HttpResponseRedirect("/tasks")


class GenericTaskEmailReportView(LoginRequiredMixin, CreateView):
    form_class = EmailReportForm
    template_name = "set_reminder.html"
    success_url = "/tasks"

    def form_valid(self, form):
        user = self.request.user
        self.object = form.save()
        self.object.user = user
        self.object.save()
        return HttpResponseRedirect("/tasks")

tasks/templates/all_tasks.html
{% extends 'base.html' %} {% block content %}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <div class="flex justify-between">
      <div class="text-center text-3xl font-bold">Hi {{request.user}}</div>
      <div>
        <form action="/user/logout/" method="post">
          {%csrf_token%}
          <button type="submit" class="text-red-500 font-semibold">
            Log out
          </button>
        </form>
      </div>
    </div>
    <div class="flex justify-evenly my-4">
      <a
        href="/tasks/all"
        class="text-purple-500 bg-purple-200 px-4 py-1 rounded-full"
        >All</a
      >
      <a href="/tasks" class="px-4 py-1">Pending</a>
      <a href="/tasks/completed" class="px-4 py-1">Completed</a>
    </div>
    <div class="text-gray-400">{{completed}} of {{all}} completed</div>
    <div class="flex flex-col flex-1">
      {%for task in tasks %} {%if task.completed%}
      <div
        class="rounded-lg my-2 bg-gray-100 flex justify-between p-4 items-center"
      >
        <a>
          <div class="font-semibold line-through text-red-500">
            {{task.title}}
          </div>
          <p class="text-gray-600">{{task.created_date}}</p>
        </a>

        <div class="flex">
          <a
            href=" /tasks/delete/{{task.id}}"
            class="leading-8 h-8 w-8 bg-red-500 rounded-md text-center"
            ><i class="fa fa-trash" style="color: white; font-size: larger"></i
          ></a>
        </div>
      </div>
      {%else%}
      <div
        class="rounded-lg my-2 bg-gray-100 flex justify-between p-4 items-center"
      >
        <a href="/tasks/task/{{task.id}}" class="leading-tight">
          <div class="font-semibold">{{task.title}}</div>
          <p class="text-gray-600">{{task.created_date}}</p>
        </a>
        <div class="flex">
          <a
            href="/tasks/update/{{task.id}}"
            class="leading-8 h-8 w-8 bg-green-400 rounded-md mr-2 text-center"
            ><i class="fa fa-pencil" style="color: white; font-size: larger"></i
          ></a>
          <a
            href="/tasks/delete/{{task.id}}"
            class="leading-8 h-8 w-8 bg-red-500 rounded-md text-center"
            ><i class="fa fa-trash" style="color: white; font-size: larger"></i
          ></a>
        </div>
      </div>
      {%endif%} {%endfor%}
      <div class="flex justify-left">
        {%for page in paginator.page_range%}
        <a
          href="?page={{page}}&search={{request.GET.search}}"
          class="px-4 rounded-full py-0 text-white bg-red-400 my-0 mx-1"
        >
          {{page}}
        </a>
        {%endfor%}
      </div>
    </div>

    <a
      href="/tasks/create/"
      class="text-center my-12 bg-red-500 text-white w-full rounded-md py-2 hover:bg-red-400 transition ease-in-out duration-300"
    >
      Create Task</a
    >
  </div>
</div>
{% endblock %}

tasks/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
      integrity="sha512-wnea99uKIC3TJF7v4eKk4Y+lMz2Mklv18+r4na2Gn1abDRPPOeef95xTzdwGD9e6zXJBteMIhZ1+68QC5byJZw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <script src="https://www.writeroo.in/inc/lib/fawesome.js"></script>

    <title>Task manager</title>
    <style>
      input {
        background-color: aliceblue;
        height: 40px;
        padding: 5px;
      }
      textarea {
        background-color: aliceblue;
        padding: 5px;
        border: 0.5px solid skyblue;
      }
      #id_completed {
        position: absolute;
        margin-top: -0.5%;
        margin-left: 2%;
      }
    </style>
  </head>

  <body>
    {% block content %}{% endblock %}
  </body>
</html>

tasks/templates/completed_tasks.html
{%extends 'base.html'%} {%block content%}
<body>
  <div
    class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
  >
    <div
      class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
    >
      <div class="flex justify-between">
        <div class="text-center text-3xl font-bold">Hi {{request.user}}</div>
        <div>
          <form action="/user/logout/" method="post">
            {%csrf_token%}
            <button type="submit" class="text-red-500 font-semibold">
              Log out
            </button>
          </form>
        </div>
      </div>
      <div class="flex justify-evenly my-4">
        <a href="/tasks/all" class="px-4 py-1">All</a>
        <a href="/tasks" class="px-4 py-1">Pending</a>
        <a
          href="/tasks/completed"
          class="text-red-500 bg-red-200 px-4 py-1 rounded-full"
          >Completed</a
        >
      </div>
      <div class="flex flex-col flex-1">
        {%for task in tasks %}
        <div
          class="rounded-lg my-2 bg-gray-100 flex justify-between p-4 items-center"
        >
          <a href="/task-details/{{task.id}}" class="leading-tight">
            <div class="font-semibold line-through text-red-500">
              {{task.title}}
            </div>
            <span class="text-gray-600">{{task.pretty_date}}</span>
          </a>
        </div>
        {%endfor%}
        <div class="flex justify-left">
          {%for page in paginator.page_range%}
          <a
            href="?page={{page}}&search={{request.GET.search}}"
            class="px-4 py-0 rounded-full text-white bg-red-500 my-0 mx-1"
          >
            {{page}}
          </a>
          {%endfor%}
        </div>
      </div>
    </div>
  </div>
  {%endblock%}
</body>

tasks/templates/set_reminder.html
{% extends 'base.html'%} {% block content%}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <form method="post">
      {%csrf_token%}
      <h1 class="text-2xl font-bold mb-4">Task Manager</h1>
      <div class="text-red-500">{{form.non_field_errors}}</div>
      <div class="font-semibold text-xl">Set Reminder</div>
      {%for field in form%}
      <div class="my-4 flex flex-col">
        <div class="mb-1">{{field.label}}</div>
        {{field}}
        <ol class="list-disc ml-6 text-sm text-red-500">
          {%if field.errors%} {%for error in field.errors %}
          <li>{{error}}</li>
          {%endfor%}
        </ol>
        {%endif%}
      </div>
      {%endfor%}
      <p class="ml-2 text-sm text-red-500">Add time in HH:MM format</p>

      <button
        type="submit"
        class="text-center bg-red-500 text-white w-full rounded-md py-2 hover:bg-red-400 transition ease-in-out duration-300"
      >
        Set Reminder
      </button>
    </form>
  </div>
</div>

{% endblock%}

tasks/templates/task_create.html
{% extends 'base.html' %} {%block content%}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <div class="h-full">
      <div class="text-2xl font-bold mb-4">Create Task</div>
      <form method="post">
        {{ form.non_field_errors }} {%csrf_token%}
        <div>
          <div class="flex flex-col mb-2">
            <span class="mb-2">Title</span>
            {{form.title}} {%if form.title.errors%}
            <ol class="list-disc ml-6 text-sm text-red-500">
              {%for error in form.title.errors %}
              <li>{{error|escape}}</li>
              {%endfor%}
            </ol>
            {%endif%}
          </div>
          <div class="flex mb-2 flex-col">
            <p class="mb-2">Description</p>
            {{form.description}} {%if form.description.errors%}
            <ol class="list-disc ml-6 text-sm text-red-500">
              {%for error in form.description.errors %}
              <li>{{error}}</li>
              {%endfor%}
            </ol>
            {%endif%}
          </div>
          <div class="">
            <div class="flex mb-3 my-4 items-center">
              <p class="mb-2 mr-2">Priority</p>
              {{form.priority}}
            </div>
            {%if form.priority.errors%}
            <ol class="list-disc ml-6 text-sm text-red-500">
              {%for error in form.priority.errors %}
              <li>{{error|escape}}</li>
              {%endfor%}
            </ol>
            {%endif%}
          </div>
          <div class="mb-2">
            <p class="ml-1">Completed {{form.completed}}</p>
          </div>
        </div>
        <button
          type="submit"
          class="text-center bg-red-500 text-white w-full rounded-md py-2 hover:bg-red-400 transition ease-in-out duration-300"
        >
          Create Task
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

tasks/templates/task_delete.html
{%extends 'base.html'%} {% block content %}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <form method="post">
      {%csrf_token%}
      <p>
        Are you sure you want to delete task "<span class="font-semibold"
          >{{object}}</span
        >" ?
      </p>
      <input
        class="border bg-red-400 text-white rounded-md cursor-pointer hover:shadow-md mt-4 p-2"
        type="submit"
        value="Confirm"
      />
    </form>
  </div>
</div>
{% endblock %}

tasks/templates/task_detail.html
{% extends 'base.html' %} {% block content %}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <div class="font-semibold text-xl">{{object.title}}</div>
    <div class="my-4 p-4 bg-gray-100 rounded-lg">{{object.description}}</div>
    <div class="">Priority : {{object.priority}}</div>
    <div>{{object.created_date}}</div>
  </div>
</div>
{% endblock %}

tasks/templates/task_update.html
{% extends 'base.html'%} {% block content %}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <div class="h-full">
      <div class="text-2xl font-bold mb-4">Update Task</div>
      <form method="post">
        {{ form.non_field_errors }} {%csrf_token%}
        <div>
          <div class="flex flex-col mb-2">
            <span class="mb-2">Title</span>
            {{form.title}} {%if form.title.errors%}
            <ol class="list-disc ml-6 text-sm text-red-500">
              {%for error in form.title.errors %}
              <li>{{error|escape}}</li>
              {%endfor%}
            </ol>
            {%endif%}
          </div>
          <div class="flex mb-2 flex-col">
            <span class="mb-2">Description</span>
            {{form.description}} {%if form.description.errors%}
            <ol class="list-disc ml-6 text-sm text-red-500">
              {%for error in form.description.errors %}
              <li>{{error|escape}}</li>
              {%endfor%}
            </ol>
            {%endif%}
          </div>
          <div class="">
            <div class="flex mb-2 items-center">
              <span class="mb-2 mr-2">Priority</span>
              {{form.priority}}
            </div>
            {%if form.priority.errors%}
            <ol class="list-disc ml-6 text-sm text-red-500">
              {%for error in form.priority.errors %}
              <li>{{error|escape}}</li>
              {%endfor%}
            </ol>
            {%endif%}
          </div>
          <div class="mb-2">
            <span class="ml-2">Completed {{form.completed}} </span>
          </div>
        </div>
        <button
          type="submit"
          class="text-center bg-red-500 text-white w-full rounded-md py-2 hover:bg-red-400 transition ease-in-out duration-300"
        >
          Update
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

tasks/templates/tasks.html
{% extends 'base.html' %} {% block content %}
<div
  class="flex border-2 p-4 h-screen align-items-center justify-center bg-gray-100"
>
  <div
    class="p-4 border sm:w-1/3 w-full rounded-lg shadow-md bg-white flex flex-col"
  >
    <div class="flex justify-between">
      <div class="text-center text-3xl font-bold">Hi {{request.user}}</div>
      <p></p>
      <div>
        <form action="/user/logout/" method="post">
          {%csrf_token%}
          <button type="submit" class="text-red-500 font-bold">Log out</button>
        </form>
      </div>
    </div>
    <div class="flex justify-evenly font-semibold my-4">
      <a href="all/" class="px-4 py-1">All</a>
      <a
        href="/tasks"
        class="text-green-500 bg-green-200 px-4 py-1 rounded-full"
        >Pending</a
      >
      <a href="completed/" class="px-4 py-1">Completed</a>
    </div>
    <div class="mb-2">
      <form method="GET" class="flex">
        <input
          type="text"
          placeholder="Search"
          name="search"
          class="bg-gray-200 rounded-l-md p-1 px-2 focus:outline-none focus:ring-2 w-2/3 border-1"
        />
        <button
          type="submit"
          class="w-1/3 bg-red-500 border border-red-600 text-white mx-0 p-1 rounded-r-md hover:bg-red-400 transition ease-in-out duration-300"
        >
          Search<i
            class="fa fa-magnifying-glass px-2"
            style="color: aliceblue; font-size: larger"
          ></i>
        </button>
      </form>
    </div>
    <div class="flex flex-1 flex-col">
      {%for task in tasks %}
      <div
        class="rounded-lg my-2 bg-gray-100 flex justify-between p-4 items-center"
      >
        <div class="flex">
          <form action="complete/{{task.id}}" method="post">
            {%csrf_token%}
            <input type="hidden" name="task_id" value="{{task.id}}" />
            <button
              class="leading-8 h-8 w-8 text-3xl rounded-md mr-2 text-center"
              type="submit"
            >
              <i class="fa fa-check" style="color: green"></i>
            </button>
          </form>
          <a href="task/{{task.id}}" class="ml-2 leading-tight">
            <div class="font-semibold">{{task.title}}</div>
            <p class="text-red-600">{{task.created_date}}</p>
          </a>
        </div>
        <div class="flex items-center">
          <a
            href="update/{{task.id}}"
            class="leading-8 h-8 w-8 bg-green-400 rounded-md mr-2 text-center"
            ><i class="fa fa-pencil" style="color: white; font-size: larger"></i
          ></a>
          <a
            href="delete/{{task.id}}"
            class="leading-8 h-8 w-8 bg-red-500 rounded-md text-center"
            ><i class="fa fa-trash" style="color: white; font-size: larger"></i
          ></a>
        </div>
      </div>
      {%endfor%}
      <div class="flex justify-left">
        {%for page in paginator.page_range%}
        <a
          href="?page={{page}}&search={{request.GET.search}}"
          class="px-4 py-0 rounded-full text-white bg-red-500 my-0 mx-1"
        >
          {{page}}
        </a>
        {%endfor%}
      </div>
    </div>
    <a
      href="create/"
      class="text-center my-12 bg-red-500 text-white w-full rounded-md py-2 hover:bg-red-400 transition ease-in-out duration-300"
    >
      Create Task</a
    >
  </div>
</div>
{% endblock %}